#!/bin/sh
set -e

escalate() {
    if [ -x "$(command -v sudo)" ]; then
        sudo $@
    else
        echo "sudo not found to escalate permissions"
        exit 1
    fi
}

if ! [ -x "$(command -v ansible-playbook)" ]; then
    case "$(uname -s)" in
        Linux)
            source /etc/os-release

            if [ "$ID" != "fedora" ]; then
                echo "[!] Unsupported Linux Distribution"
                exit 1
            fi

            escalate dnf install --assumeyes ansible
            ;;
        *)
            echo "[!] Unsupported OS"
            exit 1
            ;;
    esac
fi
