#!/bin/sh
set -e

repo_dir=$(realpath $(dirname "$0"))

escalate() {
    if [ -x "$(command -v sudo)" ]; then
        sudo $@
    elif [ -x "$(command -v doas)" ]; then
        doas $@
    else
        echo "No sudo or doas found to escalate permissions"
        exit 1
    fi
}

if ! [ -x "$(command -v ansible-playbook)" ]; then
    case "$(uname -s)" in
        FreeBSD)
            escalate pkg install --yes sysutils/ansible
            ;;
        Linux)
            source /etc/os-release

            if [ "$ID" != "fedora" ]; then
                echo "[!] Unsupported Linux Distrobution"
                exit 1
            fi

            escalate dnf install --assumeyes ansible
            ;;
        *)
            echo "[!] Unsupported OS"
            exit 1
            ;;
    esac
fi

export ANSIBLE_LOCALHOST_WARNING=false
ansible-playbook --ask-become-pass "$repo_dir/ansible/setup.yaml"

